import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowLeft, CalendarDays, Clock3, MapPin, Users } from 'lucide-react'
import { prisma } from '@/lib/prisma'
import JoinMinyanButton from '@/components/join-minyan-button'

export const dynamic = 'force-dynamic'
export default async function MinyanDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const minyan = await prisma.minyan.findFirst({ where: { id, status: 'ACTIVE', expiresAt: { gt: new Date() } }, include: { city: true, country: true, _count: { select: { participants: true } } } })
  if (!minyan) notFound()
  return <main className="min-h-screen bg-[#f7f7f2] text-[#183f52]"><header className="border-b border-[#dfe5e0] bg-white/80 px-5 backdrop-blur md:px-10"><div className="mx-auto flex h-[74px] max-w-[980px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#183f52] text-lg tracking-[-.08em] text-white">תד</span><span className="text-sm font-semibold">Tefilat Ha-Derech</span></Link><Link href="/dashboard" className="rounded-full border border-[#b9c7c5] px-4 py-2 text-sm font-semibold hover:bg-white">Dashboard</Link></div></header><section className="mx-auto max-w-[780px] px-5 py-10 md:px-10 md:py-14"><Link href="/#minyanim" className="inline-flex items-center gap-2 text-sm font-semibold text-[#d57561]"><ArrowLeft size={16} /> Back to minyanim</Link><article className="mt-8 overflow-hidden rounded-[30px] border border-[#dfe5e0] bg-white shadow-[0_18px_55px_rgba(24,63,82,.08)]"><div className="bg-[#183f52] px-6 py-10 text-white md:px-10"><span className="inline-flex rounded-full bg-[#e0eee5] px-3 py-1 text-xs font-semibold text-[#54816e]">{minyan.type === 'RECURRING' ? 'Recurring gathering' : 'One-time gathering'}</span><h1 className="mt-5 text-4xl font-medium leading-tight tracking-[-.06em] md:text-5xl">{minyan.title}</h1><p className="mt-4 text-sm text-[#b7d1c4]">A welcoming prayer gathering for Jewish travelers and friends.</p></div><div className="p-6 md:p-10">{minyan.description && <p className="text-[16px] leading-7 text-[#718489]">{minyan.description}</p>}<div className="mt-8 grid gap-3 sm:grid-cols-2"><Info icon={Clock3} label="When" value={minyan.startDateTime.toLocaleString()} /><Info icon={MapPin} label="Where" value={`${minyan.city?.name ?? minyan.address ?? 'Location to be confirmed'}${minyan.country ? `, ${minyan.country.name}` : ''}`} /><Info icon={Users} label="Community" value={`${minyan._count.participants} people joined`} /><Info icon={CalendarDays} label="Prayer" value={minyan.prayerType.toLowerCase()} /></div><div className="mt-8 border-t border-[#edf0ed] pt-8"><JoinMinyanButton minyanId={minyan.id} /></div></div></article></section></main>
}
function Info({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <div className="rounded-2xl bg-[#f7f7f2] p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.12em] text-[#6b9a83]"><Icon size={15} />{label}</div><p className="mt-2 text-sm leading-5 text-[#718489]">{value}</p></div> }
void dynamic
void notFound
