'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, Check, Clock3, Compass, Filter, Heart, MapPin, Search, ShieldCheck, Sparkles, Star, Users } from 'lucide-react'

export type DiscoveryCard = { title: string; subtitle: string; detail: string; tag: string; tone: 'coral' | 'green' | 'gold' | 'blue'; rating?: string }

const palette = {
  coral: 'bg-[#f6e2dc] text-[#bd614f]', green: 'bg-[#e0eee5] text-[#54816e]', gold: 'bg-[#f6edcf] text-[#a78337]', blue: 'bg-[#e0ebef] text-[#356579]',
}

export function DiscoveryPage({ eyebrow, title, description, cards, searchPlaceholder, actionLabel }: { eyebrow: string; title: string; description: string; cards: DiscoveryCard[]; searchPlaceholder: string; actionLabel: string }) {
  const [query, setQuery] = useState('')
  const [saved, setSaved] = useState<string[]>([])
  const visible = useMemo(() => cards.filter((card) => `${card.title} ${card.subtitle} ${card.detail}`.toLowerCase().includes(query.toLowerCase())), [cards, query])

  return <main className="min-h-screen bg-[#f7f7f2] text-[#183f52]">
    <header className="border-b border-[#dfe5e0] bg-[#f7f7f2]/95 px-5 backdrop-blur md:px-10"><div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between"><a href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-[#183f52] text-lg font-semibold tracking-[-.08em] text-white">תד</span><span className="text-[15px] font-semibold">Tefilat Ha-Derech</span></a><nav className="hidden gap-7 text-[13px] font-medium text-[#5e737e] md:flex"><a href="/">Home</a><a href="/dashboard">Dashboard</a><a className="text-[#183f52]" href="#top">Explore</a></nav><a href="/login" className="rounded-full border border-[#b9c7c5] px-5 py-2.5 text-[13px] font-semibold">Log in</a></div></header>
    <section className="px-5 pb-12 pt-14 md:px-10 md:pt-20"><div className="mx-auto max-w-[1240px]"><p className="mb-3 text-[12px] font-semibold uppercase tracking-[.15em] text-[#6b9a83]">{eyebrow}</p><div className="max-w-3xl"><h1 className="text-[clamp(2.8rem,6vw,5rem)] font-medium leading-[.96] tracking-[-.06em]">{title}</h1><p className="mt-6 max-w-2xl text-[17px] leading-7 text-[#6b7d83]">{description}</p></div><div className="mt-9 flex max-w-2xl items-center gap-2 rounded-[20px] border border-[#c8d4d1] bg-white p-2 shadow-[0_16px_45px_rgba(24,63,82,.07)]"><Search className="ml-3 shrink-0 text-[#d57561]" size={19}/><input aria-label="Search" value={query} onChange={(e) => setQuery(e.target.value)} placeholder={searchPlaceholder} className="min-w-0 flex-1 bg-transparent px-2 py-3 text-sm outline-none placeholder:text-[#9aa9aa]"/><button type="button" aria-label="Apply search" className="rounded-[14px] bg-[#183f52] px-5 py-3.5 text-sm font-semibold text-white"><Filter size={17}/></button></div></div></section>
    <section className="border-y border-[#dfe5e0] bg-white/60 px-5 py-4 md:px-10"><div className="mx-auto flex max-w-[1240px] flex-wrap gap-3 text-[12px] text-[#6b7d83]"><span className="rounded-full bg-[#e0eee5] px-3 py-2 font-semibold text-[#54816e]">{visible.length} results</span><span className="rounded-full border border-[#dfe5e0] px-3 py-2">All destinations</span><span className="rounded-full border border-[#dfe5e0] px-3 py-2">Community verified</span></div></section>
    <section className="px-5 py-12 md:px-10 md:py-16"><div className="mx-auto max-w-[1240px]"><div className="mb-7 flex items-end justify-between"><div><h2 className="text-2xl font-semibold tracking-[-.03em]">Explore the community</h2><p className="mt-2 text-sm text-[#7e8e91]">Information shared by travelers and local community members.</p></div><button className="hidden rounded-full bg-[#183f52] px-5 py-3 text-sm font-semibold text-white sm:block">{actionLabel}</button></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map((card) => <article key={card.title} className="rounded-[22px] border border-[#dfe5e0] bg-white p-5 transition hover:-translate-y-1 hover:shadow-[0_18px_50px_rgba(24,63,82,.09)]"><div className="mb-7 flex items-start justify-between"><span className={`rounded-full px-3 py-1 text-[11px] font-semibold ${palette[card.tone]}`}>{card.tag}</span><button aria-label={`Save ${card.title}`} onClick={() => setSaved((items) => items.includes(card.title) ? items.filter((item) => item !== card.title) : [...items, card.title])} className="text-[#a5b1b1] hover:text-[#d57561]"><Heart size={19} fill={saved.includes(card.title) ? 'currentColor' : 'none'}/></button></div><h3 className="text-lg font-semibold">{card.title}</h3><p className="mt-2 text-sm text-[#6b7d83]">{card.subtitle}</p><div className="mt-5 space-y-2 text-[13px] text-[#738488]"><p className="flex items-center gap-2"><MapPin size={15} className="text-[#d57561]"/>{card.detail}</p>{card.rating && <p className="flex items-center gap-2"><Star size={15} className="text-[#a78337]"/> {card.rating}</p>}</div><div className="mt-6 flex items-center justify-between border-t border-[#edf0ed] pt-4 text-[12px] text-[#7d8d8f]"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-[#6b9a83]"/> Community shared</span><ArrowRight size={16} className="text-[#d57561]"/></div></article>)}</div>{visible.length === 0 && <div className="rounded-2xl border border-dashed border-[#b9c7c5] bg-white p-12 text-center text-sm text-[#6b7d83]">No results yet. Try another destination.</div>}</div></section>
    <section className="bg-[#183f52] px-5 py-14 text-white md:px-10"><div className="mx-auto flex max-w-[1240px] items-center justify-between gap-5"><div><p className="mb-2 text-[12px] font-semibold uppercase tracking-[.15em] text-[#b7d1c4]">Help someone on their way</p><h2 className="text-2xl font-medium">Know a place worth sharing?</h2></div><a href="/dashboard" className="rounded-full bg-[#f1d5a5] px-5 py-3 text-sm font-semibold text-[#183f52]">Add information</a></div></section>
  </main>
}

export const places: DiscoveryCard[] = [
  { title: 'Chabad of Florence', subtitle: 'Chabad house · Open to visitors', detail: 'Florence, Italy', tag: 'Chabad', tone: 'blue', rating: '4.9 · 128 community reviews' },
  { title: 'Great Synagogue of Rome', subtitle: 'Synagogue · Historic community', detail: 'Rome, Italy', tag: 'Synagogue', tone: 'green', rating: '4.8 · 94 community reviews' },
  { title: 'Chabad Central Park', subtitle: 'Synagogue & Chabad', detail: 'New York, USA', tag: 'Both', tone: 'gold', rating: '4.7 · 56 community reviews' },
]

export const kosher: DiscoveryCard[] = [
  { title: 'Bamba Peanut Snack', subtitle: 'Osem · Snacks', detail: 'Jerusalem, Israel', tag: 'Kosher info', tone: 'gold' },
  { title: 'Local dairy selection', subtitle: 'Supermercato · Dairy', detail: 'Rome, Italy', tag: 'Community note', tone: 'green' },
  { title: 'Travel pantry essentials', subtitle: 'Products shared by travelers', detail: 'New York, USA', tag: 'Popular', tone: 'coral' },
]

export const trips: DiscoveryCard[] = [
  { title: 'A soulful weekend in Safed', subtitle: '3 days · Jewish heritage & nature', detail: 'Safed, Israel', tag: 'Guide trip', tone: 'green', rating: 'By Miriam Cohen' },
  { title: 'Florence with intention', subtitle: '5 days · Food, art & community', detail: 'Florence, Italy', tag: 'Guide trip', tone: 'coral', rating: 'By David Levi' },
  { title: 'Family New York discovery', subtitle: '7 days · Kid-friendly recommendations', detail: 'New York, USA', tag: 'Guide trip', tone: 'blue', rating: 'By Sarah Adler' },
]

export function StatsStrip() { return <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#e0eee5] p-4"><Users className="text-[#54816e]" size={18}/><p className="mt-4 text-2xl font-semibold">2,480</p><p className="text-xs text-[#6b7d83]">community members</p></div><div className="rounded-2xl bg-[#f6edcf] p-4"><Compass className="text-[#a78337]" size={18}/><p className="mt-4 text-2xl font-semibold">186</p><p className="text-xs text-[#6b7d83]">destinations covered</p></div><div className="rounded-2xl bg-[#e0ebef] p-4"><Clock3 className="text-[#356579]" size={18}/><p className="mt-4 text-2xl font-semibold">420</p><p className="text-xs text-[#6b7d83]">active minyanim</p></div></div> }

export function GuideLanding() { return <main className="min-h-screen bg-[#f7f7f2] px-5 py-10 text-[#183f52] md:px-10 md:py-16"><div className="mx-auto max-w-[1100px]"><a href="/" className="text-sm font-semibold text-[#6b9a83]">← Back home</a><div className="mt-14 grid gap-12 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="mb-3 text-[12px] font-semibold uppercase tracking-[.15em] text-[#d57561]">For local guides</p><h1 className="text-[clamp(3rem,7vw,6rem)] font-medium leading-[.92] tracking-[-.07em]">Share the way<br/><em className="font-serif font-normal text-[#d57561]">you know it.</em></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#6b7d83]">Create thoughtful trips and recommendations that help Jewish travelers feel at home, wherever they land.</p><a href="/login" className="mt-8 inline-flex rounded-full bg-[#183f52] px-6 py-3.5 text-sm font-semibold text-white">Become a guide <ArrowRight className="ml-2" size={17}/></a></div><StatsStrip/></div><div className="mt-20 grid gap-4 md:grid-cols-3">{['Build your guide profile','Curate meaningful trips','Help travelers connect'].map((item, i) => <div className="rounded-2xl border border-[#dfe5e0] bg-white p-5" key={item}><span className="grid size-9 place-items-center rounded-xl bg-[#e0eee5] text-sm font-semibold text-[#54816e]">0{i+1}</span><h2 className="mt-8 font-semibold">{item}</h2><p className="mt-2 text-sm leading-6 text-[#6b7d83]">Your local knowledge becomes a trusted companion for someone else's journey.</p></div>)}</div></div></main> }

export function AdminLanding() { return <main className="min-h-screen bg-[#f7f7f2] px-5 py-10 text-[#183f52] md:px-10"><div className="mx-auto max-w-[1240px]"><div className="flex items-center justify-between"><div><a href="/" className="text-sm font-semibold text-[#6b9a83]">← Home</a><p className="mt-8 text-[12px] font-semibold uppercase tracking-[.15em] text-[#d57561]">Administration</p><h1 className="mt-2 text-4xl font-medium tracking-[-.05em]">Community operations</h1></div><a href="/dashboard" className="rounded-full border border-[#b9c7c5] px-4 py-2 text-sm font-semibold">Back to dashboard</a></div><div className="mt-10"><StatsStrip/></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{['Pending approvals','Users','Guide profiles','Reports'].map((item, i) => <a href="#" key={item} className="rounded-2xl border border-[#dfe5e0] bg-white p-5 transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-center justify-between"><span className="text-sm font-semibold">{item}</span><ArrowRight size={16} className="text-[#d57561]"/></div><p className="mt-8 text-3xl font-semibold">{[12, 2480, 34, 7][i]}</p><p className="mt-1 text-xs text-[#7e8e91]">Needs your attention</p></a>)}</div><div className="mt-10 rounded-[22px] border border-[#dfe5e0] bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Recent submissions</h2><p className="mt-1 text-sm text-[#7e8e91]">Review community content before it goes live.</p></div><button className="rounded-full bg-[#183f52] px-4 py-2.5 text-sm font-semibold text-white">View queue</button></div><div className="mt-6 divide-y divide-[#edf0ed]">{['Chabad of Lisbon','Shabbat dinner in Prague','Kosher products in Athens'].map((item) => <div className="flex items-center justify-between py-4" key={item}><div><p className="text-sm font-semibold">{item}</p><p className="mt-1 text-xs text-[#7e8e91]">Submitted today · Pending review</p></div><span className="rounded-full bg-[#f6edcf] px-3 py-1 text-xs font-semibold text-[#a78337]">Pending</span></div>)}</div></div></div></main> }

export function AboutPage() { return <main className="min-h-screen bg-[#183f52] px-5 py-10 text-white md:px-10 md:py-16"><div className="mx-auto max-w-[1000px]"><a href="/" className="text-sm font-semibold text-[#b7d1c4]">← Back home</a><div className="py-24"><p className="text-[12px] font-semibold uppercase tracking-[.15em] text-[#f1d5a5]">Our why</p><h1 className="mt-5 max-w-3xl text-[clamp(3rem,7vw,6rem)] font-medium leading-[.94] tracking-[-.07em]">Every journey deserves a place to feel <em className="font-serif font-normal text-[#d57561]">connected.</em></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#c6d3d2]">Tefilat Ha-Derech brings Jewish travelers, local communities and thoughtful guides together in one trusted place.</p></div><div className="grid gap-4 md:grid-cols-3">{['Community first','Shared with care','Built for the way'].map((item) => <div className="rounded-2xl border border-white/15 bg-white/5 p-5" key={item}><Check className="text-[#b7d1c4]" size={20}/><h2 className="mt-8 font-semibold">{item}</h2><p className="mt-2 text-sm leading-6 text-[#c6d3d2]">Useful information, clearly shared, for the next person on the road.</p></div>)}</div></div></main> }
